### ISSUE TITLE
(URGENT) Crashing when fetching NIST IRs

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#108]
From https://github.com/metanorma/mn-samples-nist/pull/90

```
bundle exec relaton fetch 'NIST IR 7788'
[relaton-nist] (NIST IR 7788) Fetching from csrc.nist.gov ...
[relaton-nist] (NIST IR 7788) Fetching from Relaton repository ...
bundler: failed to load command: relaton (/Users/me/.asdf/installs/ruby/3.2.2/bin/relaton)
/Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/open-uri.rb:369:in `open_http': 404 Not Found (OpenURI::HTTPError)
	from /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/open-uri.rb:760:in `buffer_open'
	from /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/open-uri.rb:214:in `block in open_loop'
	from /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/open-uri.rb:212:in `catch'
	from /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/open-uri.rb:212:in `open_loop'
	from /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/open-uri.rb:153:in `open_uri'
	from /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/relaton-nist-1.17.0/lib/relaton_nist
```

Full list:
```
[relaton] ERROR: `NIST IR 7788` -- 404 Not Found
[relaton] ERROR: `NIST IR 7622` -- 404 Not Found
[relaton] ERROR: `NIST IR 7849` -- 404 Not Found
[relaton] ERROR: `NIST IR 7870` -- 404 Not Found
[relaton] ERROR: `NIST IR 7676` -- 404 Not Found
[relaton] ERROR: `NIST IR 7539` -- 404 Not Found
[relaton] ERROR: `NIST IR 7559` -- 404 Not Found
[relaton] ERROR: `NIST IR 7874` -- 404 Not Found
[relaton] ERROR: `NIST IR 7956` -- 404 Not Found
[relaton] ERROR: `NIST IR 7817` -- 404 Not Found
[relaton] ERROR: `NIST IR 7966` -- 404 Not Found
[relaton] ERROR: `NIST IR 8011-2` -- 404 Not Found
[relaton] ERROR: `NIST IR 8040` -- 404 Not Found
[relaton] ERROR: `NIST IR 8011-1` -- 404 Not Found
[relaton] ERROR: `NIST IR 8011-4` -- 404 Not Found
[relaton] ERROR: `NIST IR 8011-3` -- 404 Not Found
[relaton] ERROR: `NIST IR 8062` -- 404 Not Found
[relaton] ERROR: `NIST IR 8112` -- 404 Not Found
[relaton] ERROR: `NIST IR 8179` -- 404 Not Found
[relaton] ERROR: `NIST IR 8023` -- 404 Not Found
[relaton] ERROR: `NIST IR 8272` -- 404 Not Found
```

**Comment by andrew2net** [comment]
The parser needed to be fixed because some documents come without DOI now. I also updated the parser so if some parsing error happens it will stop parsing and a notification will be emailed.
